highlighter:    rouge
permalink:      ./:title
name:           Benny
description:    "Weak notes"
author:         "Mat Benfield"
url:            https://thechels.uk
copyright:      "Mat Benfield"
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
