highlighter:    rouge
permalink:      ./:title
title:           "Weak Notes"
description:    "typically less than weekly stuff and things"
author:         "Mat"
url:            https://thechels.uk
copyright:      "Mat B"
encoding:       UTF-8
future:         false
twitter:
  username: "@tocfcws"
github:
  repository_url: https://github.com/MatBenfield/TheChels.uk/
  branch: main
exclude:        ["README"]
sass:
  style:        compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
