highlighter:    rouge
permalink:      ./:title
title:           "Weak Notes"
description:    "typically less than weekly stuff and things"
author:         "Mat"
url:            https://thechels.uk
copyright:      "Mat B"
encoding:       UTF-8
future:         false
ad:
  message: "ad: your ad here"
social:
  twitter: https://twitter.com/tocfcws
  twitterid: "@tocfcws"
  github: https://github.com/MatBenfield/
github:
  repository_url: https://github.com/MatBenfield/TheChels.uk
  branch: main
exclude:
  "README"
  "python"
  "requirements.text"
  "config"
sass:
  style:        compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
