highlighter:    rouge
permalink:      ./:title
name:           TheChels
description:    "Father, Husband, Gentleman, Runner, Lead Software Developer, Product Owner, Tester, Analyst, ScrumMaster, Automator, Carefree, Liberal, and Champion."
author:         ChelseaStats
url:            https://matbenfield.github.io
copyright:      "Mat Benfield"
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
