highlighter:    rouge
permalink:      ./:title
title:           "Weak Notes"
description:    "a collection of stuff and things"
author:         "Mat"
twitter:        "@tocfcws"
url:            https://thechels.uk
copyright:      "Mat B"
encoding:       UTF-8
future:         false
repository:     MatBenfield/TheChels.uk
defaultImagePath: "/images/splashscreens/apple-touch-icon-180x180.png"
github:
  repository_url: https://github.com/MatBenfield/TheChels.uk
  branch: main
sass:
  style:
    compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
-
  link: "https://thechels.uk/about"
  title: "About"
-
  link: "https://thechels.uk/cv"
  title: "CV"
-
  link: "https://thechels.uk/contact"
  title: "Contact"
-
  link: "https://thechels.uk/offers"
  title: "Offers"  
## Footer
navigation_footer:
-
  link: "https://thechels.uk/feed.json"
  title: "Feed"
-
  link: "https://thechels.uk/humans.txt"
  title: "Humans"
-
  link: "https://thechels.uk/robots.txt"
  title: "Robots"
-
  link: "https://thechels.uk/sitemap.xml"
  title: "Sitemap"
-
  link: "https://thechels.uk/.well-known/security.txt"
  title: "Security"
## Around the web
around_the_web:
-
  link: "https://github.com/MatBenfield/"
  title: "GitHub"
-
  link: "https://www.linkedin.com/in/mat-benfield/"
  title: "LinkedIn"
-
  link: "https://www.meetup.com/members/197754442/"
  title: "MeetUp"
-
  link: "https://bit.ly/2W7zxUB"
  title: "Acorn's Children Hospice"
