highlighter:    rouge
permalink:      ./:title
name:           "Weak Notes"
description:    "typically less than weekly things of note"
author:         "Mat"
url:            https://thechels.uk
copyright:      "Mat Benfield"
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
