highlighter:    rouge
permalink:      ./:title
name:           TheChels
description:    "bits and pieces"
author:         ChelseaStats
url:            https://thechels.uk
copyright:      "<a href='https://twitter.com/ChelseaStats'>ChelseaStats</a> Limited, Registered in England and Wales. Company Number 07269584."
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
