highlighter:    rouge
permalink:      ./:title
title:           "Weak Notes"
description:    "a collection of stuff and things"
author:         "Mat"
url:            https://thechels.uk
copyright:      "Mat B"
encoding:       UTF-8
future:         false
github:
  repository_url: https://github.com/MatBenfield/TheChels.uk
  branch: main
sass:
  style:
    compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
exclude:
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
include:
  - ".well-known"
  - "_pages"
