highlighter:    rouge
permalink:      ./:title
name:           "Weak notes"
description:    "Mat Benfield"
author:         "Benny"
url:            https://thechels.uk
copyright:      "Mat Benfield"
encoding:       UTF-8
future:         false
exclude:        ["README"]
sass:
  style:        compressed
gems:
  - jekyll-feed
