name: Add podcast
description: Update my podcast library
title: "New Podcast: "
labels: 'podcasts'
assignees: 'Mat-0'
body:
  - type: textarea
    id: logs
    attributes:
      label: "Add Data"
      description: Add values to the yaml below
      value: |
       -
          category:
          link: ""
          name: ""
      render: yaml
