name: Add podcast
description: Update my podcast library
title: "New Podcast: "
labels: 'podcasts'
assignees: 'MatBenfield'
body:
  - type: textarea
    id: logs
    attributes:
      label: " "
      description: Add values to the yaml below
      value: |
        -
          category:
          link: ""
          name: ""
      render: yaml
