name: Contact
description: Simple way to message me - please note these are public
title: "[Contact] <title>"
labels: [Contact]
body:
- type: textarea
  attributes:
    label: Subject
    description: What is the detail?
  validations:
    required: false
- type: textarea
  attributes:
    label: Your message
    description: What is the detail?
  validations:
    required: false
