name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - matbenfield
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

