name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - matbenfield
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
- type: textarea
    id: what-problem
    attributes:
      label: A clear and concise description of what the problem is. E.g., I am always frustrated when
      description: A clear and concise description of what the problem is. E.g., I am always frustrated when
      placeholder: ""
      value: ""
    validations:
      required: true
- type: textarea
    id: what-you-want
    attributes:
      label: A clear and concise description of what you want to happen
      description: A clear and concise description of what you want to happen
      placeholder: ""
      value: ""
    validations:
      required: true
- type: textarea
    id: what-you-have-tried
    attributes:
      label: A clear and concise description of any alternative solutions or features you have considered.
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: ""
      value: ""
    validations:
      required: true      
- type: textarea
    id: what-else
    attributes:
      label: Anything else you would like to add.
      description: Useful additional context.
      placeholder: ""
      value: ""
    validations:
      required: false  
