name: Add Podcast
on:
  issues:
    types: [opened, labeled]

jobs:
  add_bookmark:
    runs-on: macOS-latest
    name: Add bookmark
    if: contains( github.event.issue.labels.*.name, 'podcast')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bookmark action
        uses: katydecorah/bookmark-action@v3.1.2
        with:
          fileName: _data/podcasts.yml
      - name: Download the thumbnail image
        run: curl "${{ env.BookmarkImage }}" -o "img/${{ env.BookmarkImageOutput }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: GitHub Action <action@github.com>
          branch: "new-post-from-issue"
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          body: |
            You bookmarked ${{ env.BookmarkTitle }} on ${{env.DateBookmarked}}.
            Automatic PR: ${{ steps.title.outputs.title }}
            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "Post: ${{ github.event.issue.title }}"
