name: Add Item
# 'next','stocks','quotes','podcasts','teams'
on:
  issues:
    types: [labeled, edited]
jobs:
  Validation:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'quotes')
    outputs:
      labelname: ${{ steps.validation.outputs.labelname }}
    steps:
      - name: Set Data
        id: validation
        run: |
          echo "labelname=quotes" >> $GITHUB_ENV
          echo "::set-output name=labelname::quotes"
  Execution:
    name: Runner
    uses: ./.github/workflows/runner.yml
    needs: Validation
    with:
      content: ${{ github.event.issue.body }}
      label: ${{ needs.Validation.outputs.labelname }}
