name: Add Item
on:
  issues:
    types: [labeled, edited]
jobs:
  Validation:
    runs-on: ubuntu-latest
    env:
      env_label: github.event.issue.label.name
    ## if: contains( github.event.issue.labels.*.name, fromJson('next','stocks','quotes','podcasts','teams')
    steps:
      - name: Set Data
        run: echo $env_label
  Execution:
    name: Runner
    uses: ./.github/workflows/runner.yml
    needs: Validation
    with:
      content: ${{ github.event.issue.body }}
      label: $env_label
