name: Add Item
on:
  issues:
    types: [labeled, edited]
jobs:
  Validation:
    runs-on: ubuntu-latest
    env:
      env_label: github.event.issue.labels.*.name
    if: contains( env_label, fromJson(['next','stocks','quotes','podcasts','teams'])
    steps:
      - name: Set Data
        run: echo "env_label=${{ env_label }}" >> $GITHUB_ENV
  Execution:
    name: Runner
    uses: ./.github/workflows/runner.yml
    needs: Validation
    with:
      content: ${{ github.event.issue.body }}
      label: ${{ env_label }}
