name: Add Podcast
on:
  issues:
    types: [opened, labelled]

jobs:
  add_bookmark:
    runs-on: macOS-latest
    name: Add bookmark
    if: contains( github.event.issue.labels.*.name, 'podcast')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bookmark action
        uses: katydecorah/bookmark-action@v3.1.2
        with:
          fileName: _data/podcast.yml
      - name: Download the thumbnail image
        run: curl "${{ env.BookmarkImage }}" -o "img/${{ env.BookmarkImageOutput }}"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m  "Added ${{ env.BookmarkTitle }} to podcast.yml"
          git push
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: "${{ env.IssueNumber }}"
          comment: "You bookmarked ${{ env.BookmarkTitle }} on ${{env.DateBookmarked}}."
