name: publish-post

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Update title
        env:
          POST_TITLE: ${{ github.event.issue.title }}
        id: title
        run: |
          POST_TITLE=$(echo "$POST_TITLE" | tr " " "-")
          echo "::set-output name=title::$(echo "$POST_TITLE")"
      - name: Generate Post
        env:
          POST_TITLE: "${{ steps.title.outputs.title }}"
          POST_BODY: "${{ github.event.issue.body }}"
          POST_DATE: "${{ steps.date.outputs.date }}"
        run: |
          cd "_posts"
          POST_FM="---\n\r title: ${POST_TITLE} \n\r layout: post \n\r date: ${POST_DATE}" \n\r ---- \n\r"
          file="${POST_DATE}-${POST_TITLE}.md"
          echo -e "${POST_FM}${POST_BODY}" >> "$file"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          body: |
            Automatic PR for publishing: ${{ steps.title.outputs.title }}
            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "Post: ${{ github.event.issue.title }} \n ${{ steps.title.outputs.body }}"
