name: Lighthouse and Accessibility
on: [pull_request, workflow_dispatch]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://thechels.uk'        
    - name: Scan for accessibility issues
      uses: microsoft/accessibility-insights-action@v2
      with:
          url: 'https://thechels.uk'
