name: Morning Run
# build and tweet
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip Caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python Dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Processing Python Scripts
      env:
          open_weather_key: ${{ secrets.OPEN_WEATHER_KEY }}
          lat: ${{ secrets.LAT_COORDS }}
          lon: ${{ secrets.LON_COORDS }}
      run: |-   
        python '_python/quotes.py'
        python '_python/stocks.py'
        python '_python/sports.py'
        python '_python/weather.py'
    - name: Commit and push
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git diff --quiet || (git add -A && git commit -m "Updated with morning run")
        git push
