name: "Runner"

on:
  workflow_call:
     inputs:
      content:
        required: true
        type: string
      label:
        required: true
        type: string

jobs:
 Build:
    runs-on: ubuntu-latest
    name: Processing
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt --quiet
      - name: Check for new content
        run: |-
          python '_python/yaml-updater.py' --content "${{ inputs.content }}" --label "${{ inputs.label }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: GitHub Action <action@github.com>
          branch: "new-config-from-issue-${{ github.event.issue.number }}"
          delete-branch: true
          title: "Feat: ${{ github.event.issue.title}}"
          body: |
            > ${{ github.event.issue.body }}
            Automatic PR for Config change: ${{ steps.title.outputs.title }}
            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "feat-${{ steps.title.outputs.title }}-#${{ github.event.issue.number }}"
