name: Update Data Files
on:
  issues:
    types: [labeled, edited]

env:
  content: ${{ github.event.issue.body }}
  label: ${{ github.event.label.name }}
  issue_number : ${{ github.event.issue.number }}

jobs:
  Permission:
    runs-on: ubuntu-latest
    name: permission check
    if: contains( github.event.issue.labels.*.name, ('stocks','quotes','now')  
    outputs:
      gooduser: ${{ steps.permission_check.conclusion }}
      baduser: ${{ steps.permission_failure.conclusion }}
    steps:
    - name: check permission
      id: permission_check
      if: github.actor == github.event.repository.owner.login
      run: |
        echo permission pass
        echo ${{ steps.permission.outputs.gooduser }}
    - name: check permission failed
      id: permission_failure
      if: github.actor != github.event.repository.owner.login
      run: |
        echo permission failure
        echo ${{ steps.permission.outputs.baduser }}
  closure:
    name: Negative permission action
    runs-on: ubuntu-latest
    needs: Permission
    if: needs.permission.outputs.gooduser != 'success'
    steps:
    - name: permission failure actions
      if: needs.permission.outputs.gooduser != 'success' && ${{ github.event.label.name }} in ('stocks','quotes','now')
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ':x: Attempt triggered by @' + context.actor + ' who is not the repository owner. `${{ github.event.label.name }}` stopped.'
          })
          github.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: '${{ github.event.label.name }}',
          })
  build:
    name: Positive permission action
    runs-on: ubuntu-latest
    needs: Permission
    if: needs.permission.outputs.gooduser == 'success' && ${{ github.event.label.name }} in ('stocks','quotes','now')
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Check for new content
      run: |-
        python '_python/updater.py'
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "GitHub Action"
        git config user.email "actions@users.noreply.github.com"
        git diff --quiet || (git add -A && git commit -m "Updated with new config")
        git push
    - name: Update issue
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 @' + context.actor + ', approval granted, updating file ...'
          })
          github.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: '${{ github.event.label.name }}',
          })
    - name: Close issue
      uses: peter-evans/close-issue@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: "Auto-closing this issue."
        token: ${{ secrets.GITHUB_TOKEN }}
