name: Update Data Files
on:
  issues:
    types: [labeled, edited]

env:
  content: ${{ github.event.issue.body }}
  label: ${{ github.event.label.name }}
  issue_number : ${{ github.event.issue.number }}

jobs:
  build:

    runs-on: ubuntu-latest

    if: needs.permission.outputs.gooduser == 'success' && ${{ github.event.label.name }} in ('stocks','quotes','next')
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Check for new content
      run: |-
        python '_python/updater.py'
#     - name: Commit and push changes
#       run: |-
#         git diff
#         git config user.name "GitHub Action"
#         git config user.email "actions@users.noreply.github.com"
#         git diff --quiet || (git add -A && git commit -m "Updated with new config")
#         git push
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          committer: GitHub <noreply@github.com>
          branch: "new-config-from-issue"
          delete-branch: true
          title: "Feat: ${{ github.event.issue.title}}"
          body: |
            Automatic PR for Config change: ${{ steps.title.outputs.title }}
            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "> ${{ github.event.issue.body }}"
